In [1]:
import numpy as np
import random
import string
from datetime import datetime
from copy import deepcopy
from copy import copy

In [26]:
class nqueens:
    def __init__(self, start_x = random.randint(0,7), start_y = random.randint(0,7)):
        self.size = 8
        self.solved = False
        print(f'Board created with starting point: {start_x},{start_y}')
        self.board = np.zeros((self.size,self.size))
        self.col_order = list(range(start_x, self.size))
        self.col_order += list(range(0,start_x))
        self.row_order = list(range(start_y, self.size))
        self.row_order += list(range(0,start_y))
        self.completed = False
        self.curr_col = 0
        self.tries = 0
        
    def check_placement(self,x,y):
        #Check column
        if 1 in self.board[y]:
            return False
        #Check row
        elif 1 in self.board[:, x]:
            return False
        #Check forward diagonal
        elif 1 in np.diag(self.board, x-y):
            return False
        #Check backwards diagonal
        elif 1 in np.diag(np.fliplr(self.board), (2-y)):
            return False
        else:
            return True
        
    def backtrack_search(self):
        self.board[self.row_order[0], self.col_order[0]] = 1
        self.curr_col+=1
        if(self.backtrack_recursion(self.col_order[self.curr_col])):
            print(f'Solution has been found as follows!:\n\n')
            for i in range(0,8):
                print(f'{self.board[i]}')
        else:
            print("A solution could not be found with the given starting position")
        
    def backtrack_recursion(self, col):
        for val in self.row_order:
            self.tries+=1
            if self.check_placement(col, val):
                self.curr_col+=1
                self.board[val][col] = 1
                if self.curr_col == self.size:
                    return True
                if (self.backtrack_recursion(self.col_order[self.curr_col+1]) & self.curr_col != 8):
                    return True
                self.curr_col-=1
                self.board[val][col] = 0
        return False

In [4]:
for i,j in zip(range(4,-1,-1),range(3,-1,-1)):
    print(f'{i}, {j}')

4, 3
3, 2
2, 1
1, 0


In [27]:
startTime = datetime.now()
board = nqueens(0, 0)
print(f'It took the following amount of time to complete, in datetime format: {datetime.now() - startTime}')

Board created with starting point: 0,0
It took the following amount of time to complete, in datetime format: 0:00:00


In [85]:
test = np.zeros((8,8))
print(test)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [108]:
row = 3
col = 7
test = np.zeros((8,8))
test[0][0] = 1
test[3][7] = 1
print(test)
print("\n")
print(test[row])
print(test[:,col])
diagonal = np.diag(test, col-row)
print("\n")
print(diagonal)
diagonal = np.diag(np.fliplr(test), 7-(col+row))
print("\n")
print(diagonal)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


[0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 0. 1. 0. 0. 0. 0.]


[0. 0. 0. 1.]


[1. 0. 0. 0. 0.]


In [83]:
row=3
col=5
if row in queens_var:
    print("Impossible placement")
if queens_var[col] != -9:
    print("Impossible placement")
for i in range(1,  8-col):
        print(f'{col+i},{row+i} ')
        print(f'{col+i},{row-i} ')
for i in range(1, 8-(8-col)):
        print(f'{col-i},{row+i} ')
        print(f'{col-i},{row-i} ')

Impossible placement
Impossible placement
6,4 
6,2 
7,5 
7,1 
4,4 
4,2 
3,5 
3,1 
2,6 
2,0 
1,7 
1,-1 


In [78]:
range(col-8)

range(0, -3)

In [57]:
range(row,8,1)

range(1, 8)

In [49]:
for i in range(col, -1 ,1):
    print(i)

In [43]:
range(row, 8, 1)

range(1, 8)

In [45]:
i = zip(range(col, -1 ,1), range(row, 8, 1))

In [47]:
list(i)

[]